name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install sqlite3
      run: | #sudo apt install -y sqlite3
        cd ~
        wget https://www.sqlite.org/2020/sqlite-autoconf-3320200.tar.gz
        tar xvfz sqlite-autoconf-3320200.tar.gz
        cd sqlite-autoconf-3320200
        ./configure --prefix=/usr/local
        make
        make install

    - name: Change permissions
      run: sudo chmod u+x *.sh

    - name: Create povoar.sql
      run: ./create-povoar.sh

    - name: Test
      run: make test
